name: Snyk Static Analysis Scan
on:
  push:
    branches: ["main" ]
  pull_request:
    branches: ["main"]

jobs:
  Snyk_SAST_Scan :
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: snyk/actions/setup@master
      - name: Perform Static Analysis Test
        continue-on-error: true
        run: |
          snyk code test --all-projects --detection-depth=4 --exclude=Dockerfile --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
